#!/bin/bash
#
# Copyright (C) 2015 The AmmoniaOS Project
# Copyright (C) 2018 The SudaMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

PROJECTPATH=(
 $ANDROID_BUILD_TOP/frameworks/base
 $ANDROID_BUILD_TOP/packages/apps/Settings
 $ANDROID_BUILD_TOP/vendor/arrow
 $ANDROID_BUILD_TOP/android
 $ANDROID_BUILD_TOP/build/make
 $ANDROID_BUILD_TOP/packages/apps/Messaging
 $ANDROID_BUILD_TOP/packages/apps/Dialer
 $ANDROID_BUILD_TOP/packages/apps/Calendar
 $ANDROID_BUILD_TOP/packages/apps/Contacts
 $ANDROID_BUILD_TOP/packages/services/Telecomm
 $ANDROID_BUILD_TOP/packages/apps/Bluetooth
 $ANDROID_BUILD_TOP/system/bt

)

PROJECTLIST=(
 _frameworks_base.git
 _packages_apps_Settings.git
 _vendor_arrow.git
 _manifest.git
 _build.git
 _packages_apps_Messaging.git
 _packages_apps_Dialer.git
 _packages_apps_Calendar.git
 _packages_apps_Contacts.git
 _packages_services_Telecomm.git
 _packages_apps_Bluetooth.git
 _system_bt.git
)

project=0
auto=0

echo -e "\\033[2J"

if [ ! -z "$1" ]; then
     echo "Start repo sync -j$1, Please wait for a while..."
     repo sync -j$1
     read -p "Start to merge ?[y/n]" No
     if [ "$No" = n ]; then
          exit 1
     fi
fi

function doName() {
     PUSHNAME="sdhz150/android${PROJECTLIST[project]}"
     if [[ "$i" =~ "vendor" ]]; then
          if [[ "$i" =~ "ArrowOS" ]]; then
               PULLNAME="ArrowOS/android${PROJECTLIST[project]}"
               PUSHNAME="sdhz150/android_vendor_arrow.git"
          else
               PULLNAME="TheMuppets/proprietary${PROJECTLIST[project]}"
          fi
     else
          PULLNAME="ArrowOS/android${PROJECTLIST[project]}"
     fi
}

function doMerge() {
     if [ "$Yes" = y ] || [ "$Yes" = "" ]; then
          cd $i
          doName
          git pull https://github.com/$PULLNAME arrow-10.0 && echo "" || exit 1
          git commit -am "Merge branch 'arrow-10.0' into arrow-10.0"
          git push https://github.com/$PUSHNAME HEAD:arrow-10.0 && echo "" || exit 1
          cd $ANDROID_BUILD_TOP
     elif [ "$Yes" = e ]; then
            exit 1
     fi
}

read -p "The main code is clean, automatic merging ?[y/n]" Auto
if [ "$Auto" = y ] || [ "$Auto" = "" ]; then
     auto=`expr $auto + 1`;
fi

for i in ${PROJECTPATH[@]}; do
     if [ ! -d $i ]; then
	  echo "$i,Did not find the directory!"
	  exit 1
     else
          if [ "$auto" != 0 ]; then
               yes | read -p "$i,Pull android${PROJECTLIST[project]} ?[y/n/e]" Yes
          else
               read -p "$i,Pull android${PROJECTLIST[project]} ?[y/n/e]" Yes
          fi
          doMerge
          project=`expr $project + 1`;
fi
done
